twos-complement/level-protocol-website

.github/workflows/test.yml
.vscode/settings.json
hardhat.config.js
package.json
test/core.js
test/skill-sets.js
test/skills.js

This PR addresses issues raised during hardhat testing that were broken by (my) eslint update. It also adds a new GitHub action to run the tests and adds hardhat tests to those that are automatically run.

Lint Tweaks

---

.babelrc
__stories__/Buttons.stories.js
__stories__/Icons.stories.js
__stories__/Typography.stories.js
components/ui/Buttons.js
components/ui/MenuBar.js
components/ui/Typography.js

This PR updates the site button component to reflect changes in the Figma and incorporate the theme typography.

Buttons Update

---

__stories__/Elevation.stories.js
components/ui/Elevation.js

Add elevation styles to Storybook

Storybook > Elevation

---

__stories__/NonInteractiveWindow.stories.js
components/ui/NonInteractiveWindow.js
components/ui/icons/CloseBold.svg
components/ui/icons/CollapseBold.svg
components/ui/icons/ZoomBold.svg
components/ui/icons/index.js

Add non-interactive window

---

.gitignore
README.md
__stories__/Footer.stories.js
components/ui/Footer.js

Storybook > Footer

---

components/ui/LevelWindow.js

This PR corrects an issue where at its widest display the window is too tall and not wide enough.

Fix Wide LVL Window Width

---

components/ui/MenuBar.js
pages/index-new.js
util/url.js

link google form in `/index-new` buttons

Setup google form for sign up

---

.env.example
README.md
util/sourcecred.js

@brolag couple minor adds for documentation, etc. for your harness branch:
* Adds env var docs.
* Adds hardcoded sourcecred env var.

Harness Updates

---

public/demo.html

Amazing work by Carlos Casanova, ready to be pulled into `/token/[id]`!

Adds Carlos's demo.

---

.env.development
.env.example
.env.production
README.md
components/ConnectButton.js
components/MintButton.js
components/contexts/Web3Context.js
hardhat.config.js
pages/mint.js
util/constants.js

* Adds optional re-click of switch network button (if closed).
* Adds explicit error message for minting multiple lvl tokens.
* Adds Alchemy.
* Adds disconnect.
* Adds injected wallet address change detection.
* Adds detection for lvl token.

More cleanup

---

components/ConnectButton.js
pages/index.js

Add Docs Link

---

components/ui/MenuBar.js
components/ui/Panel.js
pages/index.js

Prod Deploy

---

components/configurator/ui/ConfiguratorPrompt.js
components/configurator/ui/ConfiguratorScreen.js
components/configurator/view/ColorConfiguratorView.js
components/configurator/view/ConnectConfiguratorView.js
components/configurator/view/NFTConfiguratorView.js
components/configurator/view/SaveConfiguratorView.js

This PR allows error messages from saving your token config (for now) and potentially for minting errors as well when minting is enabled.
I also updated the handling of the screen to remove the in-screen nav when not needed to bring it closer to Figma spec. and gave the prompt the ability to indicate the B button action.

Allow Error Messages; Add B Prompt

---

components/contexts/CommunityContext.js
components/views/CoordinapeView.js
components/views/SourcecredView.js
pages/api/admin/[address].js
pages/api/coordinape.js
pages/api/harness.js
pages/api/integrations/coordinape.js
pages/api/integrations/sourcecred.js
pages/api/rollup/[cid].js
pages/api/save-config.js
pages/api/sourcecred.js
pages/api/webhooks/coordinape.js
pages/api/webhooks/sourcecred.js
pages/token/[address].js
util/fauna.js
util/web3Storage.js

This PR just handles a variety of lint warnings to clean up the code.

Quick Lint Warning Clear

---

contracts/LvlV1.sol
contracts/SkillsV1.sol
hardhat.config.js

This PR bumps the solidity version and adds `MIT` as the license, but is that the best choice here? Any other license we should consider/select?

Fix Hardhat Test Run / Github Action

---

components/contexts/ConfiguratorContext.js

Randomized H and L
Note:
What do we think about pulling all the logic from the View into the Context? 
I copied the constants from the view over, but then I thought it seems like the view could be dumber, maybe?

Making Hue and Lightness Random

---

README.md
schemas/schema.gql

Adding Fauna instructions along with quick Loom video.

Fauna Instructions

---

components/configurator/view/NFTConfiguratorView.js
components/token/view/TokenView.js

This addition fixes the issue of loading user NFTs.
Previously we were trying to pull nfts metadata but in the first request we were making it was returning the metadata that we needed and by making the second request we were parsing data the wrong way which was causing it to fail
More details: https://app.dework.xyz/indiedao/lvl-protocol?taskId=655e7a60-610c-46cd-81db-730e2a35dfb7
No setup needed
- lvlprotocol url
- Go to join
- go through lvldex steps till you list the NFTs of your wallet
- You should be able to see all your nfts listed

Fix NFT loading issue

---

package-lock.json

Nv develop main merge fix

---

components/configurator/view/ColorConfiguratorView.js
components/configurator/view/NFTConfiguratorView.js
components/contexts/ConfiguratorContext.js
components/token/view/TokenView.js

This PR refactors the flow of the NFT metadata into a single source of truth
More details: https://app.dework.xyz/indiedao/lvl-protocol?taskId=00ac41ea-eb9d-411b-adbd-730508e4fff1
No setup needed
- lvlprotocol url
- Go to join
- go through lvldex steps till you list the NFTs of your wallet
- You should be able to see all your nfts and your ens

Refactor nft data flow

---

components/access-list/assets/envelope-open.svg
components/access-list/ui/Icon.js
components/access-list/ui/Toast.js
components/access-list/ui/Toast.stories.js
components/access-list/ui/Typography.js
pages/access-list.js
util/theme.js

This PR adds the toast UI and drops it into the page. Review #107 first as this builds atop it. :)

Access List > Toast UI

---

components/access-list/ui/Header.js
components/access-list/ui/Hero.js
components/access-list/ui/Member.js
components/access-list/ui/Toast.js
pages/access-list.js

This PR updates the page layout to accommodate changes made to the UI components. This PR should only be reviewed after #111, as it follows on it.
https://www.loom.com/share/59477adda1a5427e979ec6f28dc9b92a

Access List > Update Page Layout
